name: Run UI-Automation Tests

on:
  push:
    branches:
      - 'master'
      - 'github-action'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run UI-Automation tests with Chrome browser
        run: ./gradlew clean test

      - name: Generate Allure report
        if: always()
        run: ./gradlew allureReport

      - name: Deploy Allure report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: build/reports/allure-report

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure report
          path: build/reports/allure-report