name: Run UI-Automation Tests

on:
  workflow_dispatch:

  push:
    branches:
      - 'github-action'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Start selenoid
      - run: curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start --browsers 'firefox:96.0;chrome:97.0'
      - name: Run UI-Automation tests with Chrome browser
        run: ./gradlew clean test